name: corecrm_api
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: corecrm_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
    restart: unless-stopped
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - 1025:1025 # SMTP server
#      - 8025:8025 # Web UI
#    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
