  name: CI
  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  jobs:
    test:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: corecrm_api
          ports:
            - 5432:5432
        redis:
          image: redis:7
          ports:
            - 6379:6379
        rabbitmq:
          image: rabbitmq:3-management
          ports:
            - 5672:5672
        elasticsearch:
          image: elasticsearch:8.15.0
          env:
            discovery.type: single-node
            xpack.security.enabled: false
          ports:
            - 9200:9200
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '18'
        - run: npm install
        - run: npm run test
        - run: npm run build
